# specify any other packages that are prerequisites like this
PREREQ_PACS=setRNG tframe

# Remove src/dsefor.f here and replace it with any fortran or C source files
# (if any) that need to be compiled for your package.
OPTIONAL_PREREQ=src/dsefor.f

# this should be left here.
include ../Makevars

# this should be left here.
default:	$(DEFAULT)

# this should be left here and should not be above the default target.
include ../Makerules
