PREREQ_PACS=tframe dse EvalEst setRNG TSdbi TSpadi TSMySQL

#  ../Makevars goes up real path not sym link, so
QC=${shell cd ../ ; pwd}

include $(QC)/Makevars 

default: $(DEFAULT)

include $(QC)/Makerules
